export interface Feedback{
    id?: number,
    frage_1?: number,
    frage_1_bemerkungen?: string,
    frage_2?:number,
    frage_2_bemerkungen?:string,
    frage_3?:number,
    frage_3_bemerkungen?:string,
    frage_4_a?:number,
    frage_4_b?:number,
    frage_4_c?:number,
    frage_4_d?:number,
    frage_4_e?:number,
    frage_4_bemerkungen?:string,
    frage_5_a?:number,
    frage_5_b?:number,
    frage_5_c?:number,
    frage_5_d?:number,
    frage_5_e?:number,
    frage_5_f?:number,
    frage_5_g?:number,
    frage_5_h?:number,
    frage_5_i?:number,
    frage_5_j?:number,
    frage_5_k?:number,
    frage_5_l?:number,
    frage_5_m?:number,
    frage_5_n?:number,
    frage_5_bemerkungen?:string,
    frage_6_a?:number,
    frage_6_b?:number,
    frage_6_c?:number,
    frage_6_d?:number,
    frage_6_e?:number,
    frage_6_bemerkungen?:string,
    frage_7?:number,
    frage_7_bemerkungen?:string,
    frage_8?:number,
    frage_9?:number,
    frage_9_bemerkungen?:string,
    allgemein?:string,
    patient_id?:number

}