export interface gyatt{
    id: number,
    gesamtpunktzahl: number,
    gy_1: number,
    gy_2a: string,
    gy_2b: string,
    gy_2c: string,
    gy_2d: string,
    gy_2e: string,
    gy_3: number,
    gy_4a: number,
    gy_4b: number,
    gy_4c: number,
    gy_4d: number,
    gy_4e: number,
    gy_4f: number,
    gy_4g: number,
    gy_4h: number,
    gy_4i: number,
    gy_4j: number,
    gy_4k: number,
    gy_4l: number,
    gy_4m: number,
    gy_4n: number,
    gy_4o: number,
}